SG_API_KEY = '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'
SG_API_USER = 'crojas-azurian'
SG_API_PASS = '_q1w2e3r4'
SG_FROM = 'crojas@azurian.com'
SG_FROM_NAME = 'Christian Rojas'